# Generated by Django 2.1 on 2018-09-21 21:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_heading', models.CharField(max_length=250)),
                ('article_body', models.TextField(max_length=50)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('article_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
