# Generated by Django 2.1 on 2018-09-21 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_heading',
            field=models.CharField(max_length=200),
        ),
    ]
